plugins {
    // Apply the java-library plugin for API and implementation separation.
    id 'java-library'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // implementation group: 'net.sf.sociaal', name: 'mason', version: '16'
    // implementation group: 'com.neko233', name: 'json-java', version: '0.3.2'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}